title: Porfolio 
description: Resumen de 1 DAW 
theme: Porfolio
color_scheme: dark

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
